title: Salita
description: A dictionary that contains *all* words from *all* languages.

theme: cayman
#remote_theme: pages-themes/cayman@v0.2.0
show_downloads: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"